# See https://pre-commit.com for more information
repos:
  # Built-in hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json

  # Go-specific hooks - using TekWizely (maintained alternative)
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      # Go formatting (gofmt is built into Go)
      - id: go-fmt

      # Go vet (static analysis) - using repo-based to avoid package context issues
      - id: go-vet-repo-mod

      # Go mod tidy
      - id: go-mod-tidy-repo

      # Go build
      - id: go-build-repo-mod

      # Go tests
      - id: go-test-repo-mod

      # Comprehensive linting with golangci-lint (includes import formatting)
      - id: golangci-lint-repo-mod
        args: [--timeout=5m]

# Exclude patterns
exclude: |
  (?x)^(
      \.git/|
      vendor/|
      .*\.pb\.go$|
      .*_generated\.go$
  )$
