name: Go Tests
on:
  push:
    branches: [ main ]
    paths:
      - '*.go'
      - '**/*.go'
      - 'Makefile'
      - 'go.sum'
      - 'go.mod'
      - '.github/workflows/go.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '*.go'
      - '**/*.go'
      - 'Makefile'
      - 'go.sum'
      - 'go.mod'
      - '.github/workflows/go.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download and setup mock-lsp-server
      run: |
        curl -L https://github.com/rockerBOO/mock-lsp-server/releases/download/v0.1.0/mock-lsp-server-linux-amd64-v0.1.0.tar.gz -o mock-lsp-server.tar.gz
        tar -xzf mock-lsp-server.tar.gz
        mv mock-lsp-server-linux-amd64 mock-lsp-server
        chmod +x mock-lsp-server
        mkdir -p bin
        mv mock-lsp-server bin/
        echo "$PWD/bin" >> $GITHUB_PATH
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.24'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1

    - name: Run tests
      run: make test
